-- 1. USERS 
CREATE TABLE public.users (
  id text NOT NULL,
  email text NOT NULL UNIQUE,
  name text,
  profile_image_url text DEFAULT ''::text,
  class_year integer,
  hide_class_year boolean DEFAULT false,
  role text DEFAULT 'user'::text,
  is_verified boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  major text,
  hide_major boolean DEFAULT false,
  is_suspended boolean NOT NULL DEFAULT false,
  phone_number text UNIQUE,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);

-- 2. LISTINGS 
CREATE TABLE public.listings (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  user_id text NOT NULL,
  title character varying NOT NULL,
  price numeric NOT NULL,
  description text,
  condition character varying NOT NULL CHECK (condition::text = ANY (ARRAY['new'::character varying, 'like_new'::character varying, 'good'::character varying, 'fair'::character varying, 'poor'::character varying]::text[])),
  category character varying NOT NULL CHECK (category::text = ANY (ARRAY['textbooks'::character varying, 'electronics'::character varying, 'furniture'::character varying, 'parking'::character varying, 'clothing'::character varying, 'tickets'::character varying, 'other'::character varying]::text[])),
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'sold'::character varying, 'traded'::character varying, 'removed'::character varying]::text[])),
  preferred_payment character varying CHECK (preferred_payment::text = ANY (ARRAY['zelle'::character varying, 'cash'::character varying, 'venmo'::character varying, 'other'::character varying]::text[])),
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  deleted_at timestamp without time zone,
  search_vector tsvector DEFAULT (setweight(to_tsvector('english'::regconfig, lower((COALESCE(title, ''::character varying))::text)), 'A'::"char") || setweight(to_tsvector('english'::regconfig, lower(COALESCE(description, ''::text))), 'B'::"char")),
  location text NOT NULL DEFAULT ''::text,
  interested_users text[],
  CONSTRAINT listings_pkey PRIMARY KEY (id),
  CONSTRAINT listings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);

-- 3. MEDIA
CREATE TABLE public.media (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  listing_id integer NOT NULL,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['photo'::character varying, 'video'::character varying]::text[])),
  url character varying NOT NULL,
  duration integer,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT media_pkey PRIMARY KEY (id),
  CONSTRAINT media_listing_id_fkey FOREIGN KEY (listing_id) REFERENCES public.listings(id)
);

-- 4. REPORTS
CREATE TABLE public.reports (
  id numeric NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  reported_user_id text,
  listing_id integer,
  reason character varying NOT NULL CHECK (reason::text = ANY (ARRAY['scam'::character varying, 'prohibited'::character varying, 'harassment'::character varying, 'counterfeit'::character varying, 'no_show'::character varying]::text[])),
  notes text,
  status character varying DEFAULT 'open'::character varying CHECK (status::text = ANY (ARRAY['open'::character varying, 'in_review'::character varying, 'resolved'::character varying]::text[])),
  resolved_by text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  reporter_id text,
  CONSTRAINT reports_pkey PRIMARY KEY (id),
  CONSTRAINT reports_listing_id_fkey FOREIGN KEY (listing_id) REFERENCES public.listings(id),
  CONSTRAINT reports_reported_user_id_fkey FOREIGN KEY (reported_user_id) REFERENCES public.users(id)
);

-- 5. ADMIN_ACTIONS
CREATE TABLE public.admin_actions (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  admin_id text NOT NULL,
  action character varying NOT NULL CHECK (action::text = ANY (ARRAY['ban_user'::character varying, 'warn_user'::character varying, 'remove_listing'::character varying, 'close_report'::character varying, 'verify_user'::character varying, 'unsuspend_user'::character varying]::text[])),
  target_type character varying NOT NULL CHECK (target_type::text = ANY (ARRAY['listing'::character varying, 'user'::character varying, 'report'::character varying]::text[])),
  target_id text NOT NULL,
  notes text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT admin_actions_pkey PRIMARY KEY (id)
);